# Generated by Django 3.1.7 on 2021-03-04 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserBorrower',
            fields=[
                ('ubid', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.borrower')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
